service: playwright-docker

frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  ecr:
    images:
      playwright-app:
        path: ./
  environment:
    NODE_ENV: production

package:
  patterns:
    - '!**/*'
    - 'app/**'
    - 'node_modules/**'
    - 'package.json'

functions:
  playwright:
    image:
      name: playwright-app
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: /
          method: any
          cors: true
