service: playwright-chromium-layer

frameworkVersion: '4'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs22.x
  deploymentBucket:
    name: ${aws:accountId}-serverless-deploys
    serverSideEncryption: AES256
    blockPublicAccess: true

layers:
  playwright:
    path: layer
    name: ${self:service}-${self:provider.stage}
    description: Playwright layer for Node.js
    compatibleRuntimes:
      - nodejs20.x
      - nodejs22.x
    licenseInfo: MIT
    retain: true

package:
  excludeDevDependencies: false

